[2024-08-13T15:41:59.453+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-13T15:41:59.482+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scrape_Province.province_models.stg_province_run manual__2024-08-13T15:05:58.590829+00:00 [queued]>
[2024-08-13T15:41:59.499+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scrape_Province.province_models.stg_province_run manual__2024-08-13T15:05:58.590829+00:00 [queued]>
[2024-08-13T15:41:59.500+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 3
[2024-08-13T15:41:59.522+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): province_models.stg_province_run> on 2024-08-13 15:05:58.590829+00:00
[2024-08-13T15:41:59.540+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=49) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-13T15:41:59.545+0000] {standard_task_runner.py:63} INFO - Started process 58 to run task
[2024-08-13T15:41:59.545+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Scrape_Province', 'province_models.stg_province_run', 'manual__2024-08-13T15:05:58.590829+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/Province_Extraction.py', '--cfg-path', '/tmp/tmpmi_fv0_z']
[2024-08-13T15:41:59.551+0000] {standard_task_runner.py:91} INFO - Job 18: Subtask province_models.stg_province_run
[2024-08-13T15:41:59.576+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-13T15:41:59.630+0000] {task_command.py:426} INFO - Running <TaskInstance: Scrape_Province.province_models.stg_province_run manual__2024-08-13T15:05:58.590829+00:00 [running]> on host ubuntu
[2024-08-13T15:41:59.821+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Scrape_Province' AIRFLOW_CTX_TASK_ID='province_models.stg_province_run' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T15:05:58.590829+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-13T15:05:58.590829+00:00'
[2024-08-13T15:41:59.825+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-13T15:41:59.920+0000] {log.py:232} WARNING - [[34m2024-08-13T15:41:59.919+0000[0m] {[34mgraph.py:[0m377} INFO[0m - [35m(astronomer-cosmos)[0m - Trying to parse the dbt project using dbt ls cache cosmos_cache__dbt_dag_filterd__customers_group...[0m
[2024-08-13T15:41:59.922+0000] {log.py:232} WARNING - [[34m2024-08-13T15:41:59.919+0000[0m] {[34mgraph.py:[0m377} INFO[0m - [35m(astronomer-cosmos)[0m - Trying to parse the dbt project using dbt ls cache cosmos_cache__dbt_dag_filterd__customers_group...[0m
[2024-08-13T15:41:59.919+0000] {graph.py:377} INFO - Trying to parse the dbt project using dbt ls cache cosmos_cache__dbt_dag_filterd__customers_group...
[2024-08-13T15:42:00.563+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.562+0000[0m] {[34mcache.py:[0m262} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance: time to calculate cache identifier cosmos_cache__dbt_dag_filterd__customers_group for current version: 0.6255251849997876[0m
[2024-08-13T15:42:00.564+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.562+0000[0m] {[34mcache.py:[0m262} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance: time to calculate cache identifier cosmos_cache__dbt_dag_filterd__customers_group for current version: 0.6255251849997876[0m
[2024-08-13T15:42:00.562+0000] {cache.py:262} INFO - Cosmos performance: time to calculate cache identifier cosmos_cache__dbt_dag_filterd__customers_group for current version: 0.6255251849997876
[2024-08-13T15:42:00.567+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.567+0000[0m] {[34mgraph.py:[0m394} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance [ubuntu|58]: The cache size for cosmos_cache__dbt_dag_filterd__customers_group is 3021[0m
[2024-08-13T15:42:00.568+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.567+0000[0m] {[34mgraph.py:[0m394} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance [ubuntu|58]: The cache size for cosmos_cache__dbt_dag_filterd__customers_group is 3021[0m
[2024-08-13T15:42:00.567+0000] {graph.py:394} INFO - Cosmos performance [ubuntu|58]: The cache size for cosmos_cache__dbt_dag_filterd__customers_group is 3021
[2024-08-13T15:42:00.570+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.570+0000[0m] {[34mgraph.py:[0m402} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance: Cache hit for cosmos_cache__dbt_dag_filterd__customers_group - e817fdfdc4cadaa2fe870bd62a4c3e2e,5f7d44698c4b67134aff532494870c9c[0m
[2024-08-13T15:42:00.572+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.570+0000[0m] {[34mgraph.py:[0m402} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance: Cache hit for cosmos_cache__dbt_dag_filterd__customers_group - e817fdfdc4cadaa2fe870bd62a4c3e2e,5f7d44698c4b67134aff532494870c9c[0m
[2024-08-13T15:42:00.570+0000] {graph.py:402} INFO - Cosmos performance: Cache hit for cosmos_cache__dbt_dag_filterd__customers_group - e817fdfdc4cadaa2fe870bd62a4c3e2e,5f7d44698c4b67134aff532494870c9c
[2024-08-13T15:42:00.573+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.573+0000[0m] {[34mgraph.py:[0m335} INFO[0m - [35m(astronomer-cosmos)[0m - Total nodes: 3[0m
[2024-08-13T15:42:00.574+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.573+0000[0m] {[34mgraph.py:[0m335} INFO[0m - [35m(astronomer-cosmos)[0m - Total nodes: 3[0m
[2024-08-13T15:42:00.573+0000] {graph.py:335} INFO - Total nodes: 3
[2024-08-13T15:42:00.576+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.575+0000[0m] {[34mgraph.py:[0m336} INFO[0m - [35m(astronomer-cosmos)[0m - Total filtered nodes: 3[0m
[2024-08-13T15:42:00.577+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.575+0000[0m] {[34mgraph.py:[0m336} INFO[0m - [35m(astronomer-cosmos)[0m - Total filtered nodes: 3[0m
[2024-08-13T15:42:00.575+0000] {graph.py:336} INFO - Total filtered nodes: 3
[2024-08-13T15:42:00.578+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.578+0000[0m] {[34mconverter.py:[0m251} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance (dbt_dag_filterd__customers_group) -  [ubuntu|58]: It took 0.659s to parse the dbt project for DAG using LoadMode.DBT_LS_CACHE[0m
[2024-08-13T15:42:00.579+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.578+0000[0m] {[34mconverter.py:[0m251} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance (dbt_dag_filterd__customers_group) -  [ubuntu|58]: It took 0.659s to parse the dbt project for DAG using LoadMode.DBT_LS_CACHE[0m
[2024-08-13T15:42:00.578+0000] {converter.py:251} INFO - Cosmos performance (dbt_dag_filterd__customers_group) -  [ubuntu|58]: It took 0.659s to parse the dbt project for DAG using LoadMode.DBT_LS_CACHE
[2024-08-13T15:42:00.584+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.584+0000[0m] {[34mproject.py:[0m35} INFO[0m - [35m(astronomer-cosmos)[0m - Project /opt/***/dags/Data_Marketplace does not have {'packages.yml', 'dependencies.yml'}[0m
[2024-08-13T15:42:00.585+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.584+0000[0m] {[34mproject.py:[0m35} INFO[0m - [35m(astronomer-cosmos)[0m - Project /opt/***/dags/Data_Marketplace does not have {'packages.yml', 'dependencies.yml'}[0m
[2024-08-13T15:42:00.584+0000] {project.py:35} INFO - Project /opt/***/dags/Data_Marketplace does not have {'packages.yml', 'dependencies.yml'}
[2024-08-13T15:42:00.591+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.591+0000[0m] {[34mproject.py:[0m35} INFO[0m - [35m(astronomer-cosmos)[0m - Project /opt/***/dags/Data_Marketplace does not have {'packages.yml', 'dependencies.yml'}[0m
[2024-08-13T15:42:00.592+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.591+0000[0m] {[34mproject.py:[0m35} INFO[0m - [35m(astronomer-cosmos)[0m - Project /opt/***/dags/Data_Marketplace does not have {'packages.yml', 'dependencies.yml'}[0m
[2024-08-13T15:42:00.591+0000] {project.py:35} INFO - Project /opt/***/dags/Data_Marketplace does not have {'packages.yml', 'dependencies.yml'}
[2024-08-13T15:42:00.598+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.598+0000[0m] {[34mproject.py:[0m35} INFO[0m - [35m(astronomer-cosmos)[0m - Project /opt/***/dags/Data_Marketplace does not have {'packages.yml', 'dependencies.yml'}[0m
[2024-08-13T15:42:00.599+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.598+0000[0m] {[34mproject.py:[0m35} INFO[0m - [35m(astronomer-cosmos)[0m - Project /opt/***/dags/Data_Marketplace does not have {'packages.yml', 'dependencies.yml'}[0m
[2024-08-13T15:42:00.598+0000] {project.py:35} INFO - Project /opt/***/dags/Data_Marketplace does not have {'packages.yml', 'dependencies.yml'}
[2024-08-13T15:42:00.601+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.601+0000[0m] {[34mconverter.py:[0m293} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance (dbt_dag_filterd__customers_group) - [ubuntu|58]: It took 0.0233s to build the Airflow DAG.[0m
[2024-08-13T15:42:00.603+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.601+0000[0m] {[34mconverter.py:[0m293} INFO[0m - [35m(astronomer-cosmos)[0m - Cosmos performance (dbt_dag_filterd__customers_group) - [ubuntu|58]: It took 0.0233s to build the Airflow DAG.[0m
[2024-08-13T15:42:00.601+0000] {converter.py:293} INFO - Cosmos performance (dbt_dag_filterd__customers_group) - [ubuntu|58]: It took 0.0233s to build the Airflow DAG.
[2024-08-13T15:42:00.606+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.605+0000[0m] {[34mlocal.py:[0m174} INFO[0m - [35m(astronomer-cosmos)[0m - Could not import dbtRunner. Falling back to subprocess for invoking dbt.[0m
[2024-08-13T15:42:00.607+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.605+0000[0m] {[34mlocal.py:[0m174} INFO[0m - [35m(astronomer-cosmos)[0m - Could not import dbtRunner. Falling back to subprocess for invoking dbt.[0m
[2024-08-13T15:42:00.605+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-08-13T15:42:00.609+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.609+0000[0m] {[34mlocal.py:[0m292} INFO[0m - [35m(astronomer-cosmos)[0m - Cloning project to writable temp directory /tmp/tmpej43vvso from /opt/***/dags/Data_Marketplace[0m
[2024-08-13T15:42:00.610+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.609+0000[0m] {[34mlocal.py:[0m292} INFO[0m - [35m(astronomer-cosmos)[0m - Cloning project to writable temp directory /tmp/tmpej43vvso from /opt/***/dags/Data_Marketplace[0m
[2024-08-13T15:42:00.609+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpej43vvso from /opt/airflow/dags/Data_Marketplace
[2024-08-13T15:42:00.622+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.620+0000[0m] {[34mlocal.py:[0m303} INFO[0m - [35m(astronomer-cosmos)[0m - Partial parse is enabled and the latest partial parse file is /opt/***/dags/Data_Marketplace/target/partial_parse.msgpack[0m
[2024-08-13T15:42:00.623+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.620+0000[0m] {[34mlocal.py:[0m303} INFO[0m - [35m(astronomer-cosmos)[0m - Partial parse is enabled and the latest partial parse file is /opt/***/dags/Data_Marketplace/target/partial_parse.msgpack[0m
[2024-08-13T15:42:00.620+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /opt/airflow/dags/Data_Marketplace/target/partial_parse.msgpack
[2024-08-13T15:42:00.700+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.699+0000[0m] {[34mconfig.py:[0m292} INFO[0m - [35m(astronomer-cosmos)[0m - Profile caching is enable.[0m
[2024-08-13T15:42:00.701+0000] {log.py:232} WARNING - [[34m2024-08-13T15:42:00.699+0000[0m] {[34mconfig.py:[0m292} INFO[0m - [35m(astronomer-cosmos)[0m - Profile caching is enable.[0m
[2024-08-13T15:42:00.699+0000] {config.py:292} INFO - Profile caching is enable.
[2024-08-13T15:42:00.740+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-13T15:42:00.762+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py", line 270, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 489, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 307, in run_command
    with self.profile_config.ensure_profile() as profile_values:
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 293, in ensure_profile
    cached_profile_path = self._get_profile_path(use_mock_values)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/config.py", line 269, in _get_profile_path
    current_profile_version = self.profile_mapping.version(self.profile_name, self.target_name, use_mock_values)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 98, in version
    profile = self.profile
              ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/snowflake/user_pass.py", line 80, in profile
    **self.mapped_params,
      ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 318, in mapped_params
    mapped_params[dbt_field] = self.get_dbt_value(dbt_field)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 295, in get_dbt_value
    value = self._get_airflow_conn_field(airflow_field)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 268, in _get_airflow_conn_field
    value = self.conn.extra_dejson.get(airflow_field)
            ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/snowflake/user_pass.py", line 65, in conn
    conn = super().conn
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/profiles/base.py", line 146, in conn
    conn = BaseHook.get_connection(self.conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_conn` isn't defined
[2024-08-13T15:42:00.781+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=Scrape_Province, task_id=province_models.stg_province_run, run_id=manual__2024-08-13T15:05:58.590829+00:00, execution_date=20240813T150558, start_date=20240813T154159, end_date=20240813T154200
[2024-08-13T15:42:00.820+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 18 for task province_models.stg_province_run (The conn_id `snowflake_conn` isn't defined; 58)
[2024-08-13T15:42:00.847+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-08-13T15:42:00.905+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-13T15:42:00.910+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
