[2024-08-14T03:39:11.739+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T03:39:11.761+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_s3_file backfill__2024-02-04T00:00:00+00:00 [queued]>
[2024-08-14T03:39:11.923+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.check_s3_file backfill__2024-02-04T00:00:00+00:00 [queued]>
[2024-08-14T03:39:11.924+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T03:39:11.941+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): check_s3_file> on 2024-02-04 00:00:00+00:00
[2024-08-14T03:39:11.953+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1456) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T03:39:11.955+0000] {standard_task_runner.py:63} INFO - Started process 1465 to run task
[2024-08-14T03:39:11.956+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'check_s3_file', 'backfill__2024-02-04T00:00:00+00:00', '--job-id', '497', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmpo9e54lof']
[2024-08-14T03:39:11.960+0000] {standard_task_runner.py:91} INFO - Job 497: Subtask check_s3_file
[2024-08-14T03:39:12.009+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.check_s3_file backfill__2024-02-04T00:00:00+00:00 [running]> on host ubuntu
[2024-08-14T03:39:12.128+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='check_s3_file' AIRFLOW_CTX_EXECUTION_DATE='2024-02-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-02-04T00:00:00+00:00'
[2024-08-14T03:39:12.130+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T03:39:12.144+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-08-14T03:39:12.145+0000] {s3.py:117} INFO - Poking for key : s3://s3-poc-data-marketplace/Weather_Data/Data_Weather-20240204.csv
[2024-08-14T03:39:12.159+0000] {base.py:84} INFO - Using connection ID 'aws_conn_poc' for task execution.
[2024-08-14T03:39:12.161+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_conn_poc', conn_type='aws') credentials retrieved from login and password.
[2024-08-14T03:39:43.260+0000] {s3.py:117} INFO - Poking for key : s3://s3-poc-data-marketplace/Weather_Data/Data_Weather-20240204.csv
[2024-08-14T03:40:13.839+0000] {s3.py:117} INFO - Poking for key : s3://s3-poc-data-marketplace/Weather_Data/Data_Weather-20240204.csv
[2024-08-14T03:40:44.559+0000] {s3.py:117} INFO - Poking for key : s3://s3-poc-data-marketplace/Weather_Data/Data_Weather-20240204.csv
[2024-08-14T03:40:45.373+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-08-14T03:40:45.374+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T03:40:45.396+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=check_s3_file, run_id=backfill__2024-02-04T00:00:00+00:00, execution_date=20240204T000000, start_date=20240814T033911, end_date=20240814T034045
[2024-08-14T03:40:45.468+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-14T03:40:45.525+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T03:40:45.530+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
