[2024-08-14T04:34:24.945+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T04:34:25.145+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-02-26T00:00:00+00:00 [queued]>
[2024-08-14T04:34:25.176+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-02-26T00:00:00+00:00 [queued]>
[2024-08-14T04:34:25.177+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T04:34:25.208+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): invoke_lambda_task> on 2024-02-26 00:00:00+00:00
[2024-08-14T04:34:25.219+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=2389) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T04:34:25.222+0000] {standard_task_runner.py:63} INFO - Started process 2391 to run task
[2024-08-14T04:34:25.222+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'invoke_lambda_task', 'backfill__2024-02-26T00:00:00+00:00', '--job-id', '574', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmpzrjcpuol']
[2024-08-14T04:34:25.226+0000] {standard_task_runner.py:91} INFO - Job 574: Subtask invoke_lambda_task
[2024-08-14T04:34:25.329+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-02-26T00:00:00+00:00 [running]> on host ubuntu
[2024-08-14T04:34:25.489+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='invoke_lambda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-02-26T00:00:00+00:00'
[2024-08-14T04:34:25.491+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T04:34:25.530+0000] {logging_mixin.py:188} INFO - Data_Weather-20240226.csv
[2024-08-14T04:34:25.531+0000] {logging_mixin.py:188} INFO - 2024/02/26
[2024-08-14T04:34:25.532+0000] {logging_mixin.py:188} INFO - {"execution_date": "2024/02/26", "file_name": "Data_Weather-20240226.csv"}
[2024-08-14T04:34:25.532+0000] {logging_mixin.py:188} INFO - https://eyzyhdwl8l.execute-api.ap-southeast-2.amazonaws.com/dev?execution_date=2024/02/26&file_name=Data_Weather-20240226.csv
[2024-08-14T04:34:55.118+0000] {logging_mixin.py:188} INFO - Failed to invoke Lambda function.
[2024-08-14T04:34:55.119+0000] {logging_mixin.py:188} INFO - Response: {"message": "Endpoint request timed out"}
[2024-08-14T04:34:55.122+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T04:34:55.123+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T04:34:55.132+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=invoke_lambda_task, run_id=backfill__2024-02-26T00:00:00+00:00, execution_date=20240226T000000, start_date=20240814T043425, end_date=20240814T043455
[2024-08-14T04:34:55.156+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-14T04:34:55.170+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-14T04:34:55.173+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
