[2024-08-14T03:01:40.186+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-14T03:01:40.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-01-12T00:00:00+00:00 [queued]>
[2024-08-14T03:01:40.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-01-12T00:00:00+00:00 [queued]>
[2024-08-14T03:01:40.363+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-14T03:01:40.377+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): invoke_lambda_task> on 2024-01-12 00:00:00+00:00
[2024-08-14T03:01:40.384+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=633) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-14T03:01:40.386+0000] {standard_task_runner.py:63} INFO - Started process 635 to run task
[2024-08-14T03:01:40.386+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Weather_Data_Extraction', 'invoke_lambda_task', 'backfill__2024-01-12T00:00:00+00:00', '--job-id', '381', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/Data_Weather_Extraction.py', '--cfg-path', '/tmp/tmp1xkquf3g']
[2024-08-14T03:01:40.389+0000] {standard_task_runner.py:91} INFO - Job 381: Subtask invoke_lambda_task
[2024-08-14T03:01:40.445+0000] {task_command.py:426} INFO - Running <TaskInstance: Weather_Data_Extraction.invoke_lambda_task backfill__2024-01-12T00:00:00+00:00 [running]> on host ubuntu
[2024-08-14T03:01:40.643+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Weather_Data_Extraction' AIRFLOW_CTX_TASK_ID='invoke_lambda_task' AIRFLOW_CTX_EXECUTION_DATE='2024-01-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='backfill__2024-01-12T00:00:00+00:00'
[2024-08-14T03:01:40.646+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-14T03:01:40.716+0000] {logging_mixin.py:188} INFO - Data_Weather-20240112.csv
[2024-08-14T03:01:40.718+0000] {logging_mixin.py:188} INFO - 2024/01/12
[2024-08-14T03:01:40.719+0000] {logging_mixin.py:188} INFO - {"execution_date": "2024/01/12", "file_name": "Data_Weather-20240112.csv"}
[2024-08-14T03:01:40.720+0000] {logging_mixin.py:188} INFO - https://eyzyhdwl8l.execute-api.ap-southeast-2.amazonaws.com/dev?execution_date=2024/01/12&file_name=Data_Weather-20240112.csv
[2024-08-14T03:02:10.350+0000] {logging_mixin.py:188} INFO - Failed to invoke Lambda function.
[2024-08-14T03:02:10.352+0000] {logging_mixin.py:188} INFO - Response: {"message": "Endpoint request timed out"}
[2024-08-14T03:02:10.357+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-14T03:02:10.359+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-14T03:02:10.381+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Weather_Data_Extraction, task_id=invoke_lambda_task, run_id=backfill__2024-01-12T00:00:00+00:00, execution_date=20240112T000000, start_date=20240814T030140, end_date=20240814T030210
[2024-08-14T03:02:10.428+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-14T03:02:10.470+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-14T03:02:10.475+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
