[2024-08-13T15:50:54.599+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-13T15:50:54.623+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Scrape_City.check_s3_file manual__2024-08-13T15:50:04.759811+00:00 [queued]>
[2024-08-13T15:50:54.869+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Scrape_City.check_s3_file manual__2024-08-13T15:50:04.759811+00:00 [queued]>
[2024-08-13T15:50:54.871+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-13T15:50:54.895+0000] {taskinstance.py:2330} INFO - Executing <Task(S3KeySensor): check_s3_file> on 2024-08-13 15:50:04.759811+00:00
[2024-08-13T15:50:54.906+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=282) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-13T15:50:54.908+0000] {standard_task_runner.py:63} INFO - Started process 284 to run task
[2024-08-13T15:50:54.909+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Scrape_City', 'check_s3_file', 'manual__2024-08-13T15:50:04.759811+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/City_Extraction.py', '--cfg-path', '/tmp/tmptrhvpcp5']
[2024-08-13T15:50:54.913+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask check_s3_file
[2024-08-13T15:50:54.938+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-08-13T15:50:54.994+0000] {task_command.py:426} INFO - Running <TaskInstance: Scrape_City.check_s3_file manual__2024-08-13T15:50:04.759811+00:00 [running]> on host ubuntu
[2024-08-13T15:50:55.203+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Scrape_City' AIRFLOW_CTX_TASK_ID='check_s3_file' AIRFLOW_CTX_EXECUTION_DATE='2024-08-13T15:50:04.759811+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-13T15:50:04.759811+00:00'
[2024-08-13T15:50:55.208+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-13T15:50:55.237+0000] {baseoperator.py:400} WARNING - S3KeySensor.execute cannot be called outside TaskInstance!
[2024-08-13T15:50:55.239+0000] {s3.py:117} INFO - Poking for key : s3://s3-poc-data-marketplace/City/city_table-20240812.csv
[2024-08-13T15:50:55.270+0000] {base.py:84} INFO - Using connection ID 'aws_conn_poc' for task execution.
[2024-08-13T15:50:55.276+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='aws_conn_poc', conn_type='aws') credentials retrieved from login and password.
[2024-08-13T15:50:56.737+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-08-13T15:50:56.738+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-13T15:50:56.762+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Scrape_City, task_id=check_s3_file, run_id=manual__2024-08-13T15:50:04.759811+00:00, execution_date=20240813T155004, start_date=20240813T155054, end_date=20240813T155056
[2024-08-13T15:50:56.857+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-13T15:50:56.922+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-13T15:50:56.927+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
