[2024-08-16T09:02:30.508+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-16T09:02:30.528+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Prediction_Model.Call_Prepare_Data_Procedure manual__2024-08-16T09:02:25.109947+00:00 [queued]>
[2024-08-16T09:02:30.537+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Prediction_Model.Call_Prepare_Data_Procedure manual__2024-08-16T09:02:25.109947+00:00 [queued]>
[2024-08-16T09:02:30.537+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-08-16T09:02:30.551+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): Call_Prepare_Data_Procedure> on 2024-08-16 09:02:25.109947+00:00
[2024-08-16T09:02:30.558+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=675) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-16T09:02:30.559+0000] {standard_task_runner.py:63} INFO - Started process 677 to run task
[2024-08-16T09:02:30.561+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Prediction_Model', 'Call_Prepare_Data_Procedure', 'manual__2024-08-16T09:02:25.109947+00:00', '--job-id', '1125', '--raw', '--subdir', 'DAGS_FOLDER/Prediction_Model.py', '--cfg-path', '/tmp/tmpg9m2iath']
[2024-08-16T09:02:30.564+0000] {standard_task_runner.py:91} INFO - Job 1125: Subtask Call_Prepare_Data_Procedure
[2024-08-16T09:02:30.607+0000] {task_command.py:426} INFO - Running <TaskInstance: Prediction_Model.Call_Prepare_Data_Procedure manual__2024-08-16T09:02:25.109947+00:00 [running]> on host ubuntu
[2024-08-16T09:02:30.713+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ducky' AIRFLOW_CTX_DAG_ID='Prediction_Model' AIRFLOW_CTX_TASK_ID='Call_Prepare_Data_Procedure' AIRFLOW_CTX_EXECUTION_DATE='2024-08-16T09:02:25.109947+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-16T09:02:25.109947+00:00'
[2024-08-16T09:02:30.716+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-16T09:02:30.729+0000] {logging_mixin.py:188} INFO - <class 'datetime.date'>
[2024-08-16T09:02:30.747+0000] {base.py:84} INFO - Using connection ID 'snowflake_conn' for task execution.
[2024-08-16T09:02:30.750+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-08-16T09:02:30.751+0000] {connection.py:1239} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2024-08-16T09:02:31.850+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-16T09:02:31.852+0000] {sql.py:487} INFO - Running statement: CALL PREPARE_DATA('2024-08-15');, parameters: None
[2024-08-16T09:02:37.178+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-16T09:02:37.179+0000] {sql.py:496} INFO - Rows affected: 1
[2024-08-16T09:02:37.180+0000] {snowflake.py:410} INFO - Rows affected: 1
[2024-08-16T09:02:37.181+0000] {snowflake.py:411} INFO - Snowflake query id: 01b6627e-3201-2e07-0009-3646000b547a
[2024-08-16T09:02:37.328+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-08-16T09:02:37.330+0000] {connection.py:762} INFO - closed
[2024-08-16T09:02:37.435+0000] {connection.py:768} INFO - No async queries seem to be running, deleting session
[2024-08-16T09:02:37.559+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-16T09:02:37.562+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-16T09:02:37.584+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Prediction_Model, task_id=Call_Prepare_Data_Procedure, run_id=manual__2024-08-16T09:02:25.109947+00:00, execution_date=20240816T090225, start_date=20240816T090230, end_date=20240816T090237
[2024-08-16T09:02:37.647+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-16T09:02:37.693+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-16T09:02:37.697+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
